version: '3.8'

services:
  postgres:
    image: postgres:17-bookworm
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 111
      POSTGRES_DB: postgres
    ports:
      - "5433:5432"
    volumes:
      - ./out/pgdata:/var/lib/postgresql/data 
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - app-network

  app:
    build: .
    ports:
      - "5050:5050"
    environment:
      - CONN_STRING=postgresql://postgres:111@postgres:5432/postgres?sslmode=disable
    depends_on:
      - postgres
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  postgres_data: